name: Generate Gradle Wrapper

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust as needed
        distribution: 'temurin'  # Use 'temurin' or 'adopt'

    - name: Download Gradle
      run: |
        curl -O https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        unzip -q gradle-7.4.2-bin.zip
        echo "${{ github.workspace }}/gradle-7.4.2/bin" >> $GITHUB_PATH  # Add Gradle to PATH

    - name: Initialize Gradle Project
      run: |
        gradle init --type basic  # Initializes a basic Gradle project

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 7.4.2  # Adjust the version as needed

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
        git commit -m "Add Gradle wrapper"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
