name: Generate Gradle Wrapper

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the version of Java you need

    - name: Download Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        unzip gradle-7.4.2-bin.zip
        cd gradle-7.4.2/bin
        ./gradle wrapper --gradle-version 7.4.2  # Adjust the version as needed

    - name: Commit Gradle Wrapper
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add gradlew gradlew.bat gradle/
        git commit -m "Add Gradle wrapper"
        git push
